# Generated by Django 3.2.8 on 2021-11-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='availble here', max_length=20),
        ),
    ]
