# Generated by Django 3.2.8 on 2021-11-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=20)),
                ('Email_Id', models.EmailField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
